kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: publish
    pull: default
    image: plugins/docker
    settings:
      auto_tag: true
      file: Dockerfile
      repo: josmo/lancement-web
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    when:
      event:
        - push
        - tag

  - name: deploy-dev
    pull: default
    image: peloton/drone-helm:0.0.3
    settings:
      chart: ./helm/lancement
      namespace: josmo
      release: lancement
      timeout: 200
      update_dependencies: true
      values:
        - "annotations.deployedDate=\"${DRONE_BUILD_CREATED}\""
        - "annotations.buildNumber=\"${DRONE_BUILD_NUMBER}\""
      wait: true
    environment:
      API_SERVER:
        from_secret: api_server
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
    when:
      branch:
        - master
      event:
        - push

